CREATE TABLE GCOREM_MACRO.RCP_BOMS (
	ID number(38) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	ITEM_MASTER_ID number(32,0) NOT NULL REFERENCES GCOREM_MACRO.RCP_MAT_ITEM_MASTERS(ID),
	BOM_NUM varchar2(50) NOT NULL ,
	BOM_NAME varchar2(50) NOT NULL,
	BOM_DESC varchar2(50) NOT NULL,
	SERVING varchar2(50) NOT NULL,
	COOK_TIME varchar2(50) NOT NULL,
	CONSTRAINT RCP_BOMS_PRIMARY_KEY PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX GCOREM_MACRO.RCP_BOMS_UNIQUE_1 ON GCOREM_MACRO.RCP_BOMS (BOM_NUM,ITEM_MASTER_ID);


CREATE TABLE GCOREM_MACRO.RCP_BOM_PART_RELS (
	ID NUMBER(38) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	BOM_ID NUMBER(38) NOT NULL REFERENCES GCOREM_MACRO.RCP_BOMS(ID),
	PARENT_ITEM_MASTER_ID NUMBER(38,0) NOT NULL REFERENCES GCOREM_MACRO.RCP_MAT_ITEM_MASTERS(ID),
	CHILD_ITEM_MASTER_ID NUMBER(38,0) NOT NULL REFERENCES GCOREM_MACRO.RCP_MAT_ITEM_MASTERS(ID),
	QTY NUMBER(32,0),
	CONSTRAINT RCP_BOM_PART_RELS_PRIMARY_KEY PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX GCOREM_MACRO.RCP_BOM_PART_RELS_UNIQUE_1 ON GCOREM_MACRO.RCP_BOM_PART_RELS  (BOM_ID,PARENT_ITEM_MASTER_ID,CHILD_ITEM_MASTER_ID);


CREATE TABLE GCOREM_MACRO.RCP_ROUTINGS (
	ID number(38) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	BOM_ID number(38) NOT NULL REFERENCES GCOREM_MACRO.RCP_BOMS(ID),
	ITEM_MASTER_ID number(32,0) NOT NULL REFERENCES GCOREM_MACRO.RCP_MAT_ITEM_MASTERS(ID),
	ROUTING_NUM number(32,0) NOT NULL,
	ROUTING_NAME varchar2(50) NOT NULL,
	ROUTING_DESC varchar2(50) NOT NULL,
	PLANNED_QTY number(32,0),
	CONSTRAINT RCP_ROUTINGS_PRIMARY_KEY PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX GCOREM_MACRO.RCP_ROUTINGS_UNIQUE_1 ON GCOREM_MACRO.RCP_ROUTINGS (BOM_ID,ROUTING_NUM,ROUTING_NAME);


CREATE TABLE GCOREM_MACRO.RCP_WORK_CENTERS (
	ID NUMBER(38) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	WORK_CENTER VARCHAR2(50) NOT NULL,
	WORK_CENTER_DESCR VARCHAR2(50),
	CONSTRAINT RCP_WORK_CENTERS_PRIMARY_KEY PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX GCOREM_MACRO.RCP_WORK_CENTERS_UNIQUE_1 ON GCOREM_MACRO.RCP_WORK_CENTERS (WORK_CENTER,WORK_CENTER_DESCR);


CREATE TABLE GCOREM_MACRO.RCP_ROUTING_STEPS (
	ID NUMBER(38) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	ROUTING_ID NUMBER(38) NOT NULL REFERENCES GCOREM_MACRO.RCP_ROUTINGS(ID),
	WORK_CENTER_ID NUMBER(38) NOT NULL REFERENCES GCOREM_MACRO.RCP_WORK_CENTERS(ID),
	ROUTING_STEPS_SEQ VARCHAR2(50) NOT NULL,
	ROUTING_STEP_DESC VARCHAR2(50) NOT NULL,
	PREP_TIME NUMBER(32,0),
	CONSTRAINT RCP_ROUTING_STEPS_PRIMARY_KEY PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX GCOREM_MACRO.RCP_ROUTING_STEPS_UNIQUE_1 ON GCOREM_MACRO.RCP_ROUTING_STEPS (ROUTING_ID,WORK_CENTER_ID,ROUTING_STEPS_SEQ);


CREATE TABLE GCOREM_MACRO.RCP_IMPLEMENTS (
	ID NUMBER(38) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	IMPLEMENTS_NAME VARCHAR2(50) NOT NULL,
	IMPLEMENTS_DESC VARCHAR2(50) NOT NULL,
	CONSTRAINT RCP_IMPLEMENTS_PRIMARY_KEY PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX GCOREM_MACRO.RCP_IMPLEMENTS_UNIQUE_1 ON GCOREM_MACRO.RCP_IMPLEMENTS (IMPLEMENTS_NAME,IMPLEMENTS_DESC);


CREATE TABLE GCOREM_MACRO.RCP_USAGE (
	ID NUMBER(38) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	BOM_PART_RELS_ID NUMBER(38) NOT NULL REFERENCES GCOREM_MACRO.RCP_BOM_PART_RELS(ID),
	ROUTING_STEPS_ID NUMBER(38) NOT NULL REFERENCES GCOREM_MACRO.RCP_ROUTING_STEPS(ID),
	IMPLEMENTS_ID NUMBER(38) NOT NULL REFERENCES GCOREM_MACRO.RCP_IMPLEMENTS(ID),
	USAGE_DESC VARCHAR2(50) NOT NULL,
	CONSTRAINT USAGE_PRIMARY_KEY PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX GCOREM_MACRO.RCP_USAGE_UNIQUE_1 ON GCOREM_MACRO.RCP_USAGE (BOM_PART_RELS_ID,ROUTING_STEPS_ID,IMPLEMENTS_ID);











x = $v("P3_ITEM");
y = $("#P3_MSRMNT").find(":selected").text();
z = $v("P3_QTY");

$s("P3_INGRDNTS",ingrdnt_list+z+" "+y+" "+x);

$("#P3_INGRDNTS").append(ingrdnt_list);


ingrdnt_list =  $("#P3_INGRDNTS").text();

ingrdnt_list = $v("P3_INGRDNTS");

ingrdnt_list
$s("P3_INGRDNTS",ingrdnt_list);








x = $v("P4_ITEM_1");
y = $("#P4_MSRMNT_1").find(":selected").text();
z = $v("P4_QTY_1");
ingrdnt_list = $v("P4_INGRDNTS_1");

$s("P4_INGRDNTS_1",ingrdnt_list+"\n"+z+" "+y+" "+x);

$("#P4_MSRMNT_1").prop('selectedIndex', 0);
$s("P4_ITEM_1","");
$s("P4_QTY_1","");
$("#P4_ITEM_1").focus();


document.getElementsByClassName("apex-item-auto-complete")[0].focus()






step = $v("P5_STEP_1");
$s("P5_STPS_INSTRCTN",step+"\n");
$s("P5_WC_1","");
$s("P5_IM_1","");
$s("P5_STEP_1","");



Notes:
Recipe: Measurements (Us:ounces,cups,spoons /metric:ml,kilos grams)
read joe celko's tree book










- Working on recipe app.
- Adding new column is quite difficlut at the moment, it says about apex collections(Not learned yet).
- Submitting records from a single form using multiple tables not possible at the moment, work around is separated through different forms.
Forms:
1. Recipe title, Description, etc.
2. List of ingredients.
3. Steps. 
- Test/Explored multiple master-detail forms and chainable modals.
- Testing Forms/Tables.


- Working on recipe app.

- Adding new column is quite difficlut at the moment, it says about apex collections(Not learned yet).

- Submitting records from a single form using multiple tables not possible at the moment, work around is separated through different forms.

Forms:

1. Recipe title, Description, etc.

2. List of ingredients.

3. Steps.

- Test/Explored multiple master-detail forms and chainable modals.

- Testing Forms/Tables.



- Working on recipe app.
- Working on modals/javascript.
- Working on oracle apex collections(For dynamic actions)
- Read SQl development book(PL/SQL).
- Testing Forms/Tables.



- Working on oracle apex collections(For dynamic actions)
- Read SQl development book(PL/SQL).
- Testing Modal/Tables.
- Working on BLOB(Image for recipe).
- Done working on prototype and now working on functions.
- Testing oracle Apex demo and tutorials.



I am very interested with the project and here’s some of my inputs:
1. Do we have existing roles or we have to create from scratch?
2. What database is used in the app, as we need to access the database for adding new fields. We also need to add fields for the new page of the new role.
3. As for the rest such as hiding /removing of buttons can easily be achieved by assigning the roles. 
4. Our main focus in the app is the roles as everything will just follow.






I also have a suggestion.
We can create a menu for roles which can only be access by superadmin(above the admin role). 
From the roles menu, we can add a new role and assign privilege dynamically such as;
- Create
- Read
- Delete
- This way you can dynamically add new roles in the future.
- For the new pages of the roles we need to work on it manually. 

